"""Fix relaciones

Revision ID: b3373290676f
Revises: 3dc089a3f2c1
Create Date: 2025-07-20 10:25:33.199133

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b3373290676f'
down_revision = '3dc089a3f2c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deudas')
    with op.batch_alter_table('categorias_gastos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('usuario_id'))

    op.drop_table('categorias_gastos')
    with op.batch_alter_table('gastos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_gastos_presupuesto'))

    op.drop_table('gastos')
    with op.batch_alter_table('familias', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('codigo_invitacion'))

    op.drop_table('familias')
    op.drop_table('etiquetas_transacciones')
    op.drop_table('planes_pago')
    op.drop_table('usuarios_familias')
    with op.batch_alter_table('categorias_ingresos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('usuario_id'))

    op.drop_table('categorias_ingresos')
    op.drop_table('usuarios_presupuestos')
    with op.batch_alter_table('etiquetas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('usuario_id'))

    op.drop_table('etiquetas')
    with op.batch_alter_table('proyecciones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_proyecciones_periodo'))

    op.drop_table('proyecciones')
    with op.batch_alter_table('ingresos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_ingresos_presupuesto'))

    op.drop_table('ingresos')
    op.drop_table('adjuntos')
    with op.batch_alter_table('periodos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('presupuesto_id'))

    op.drop_table('periodos')
    with op.batch_alter_table('transacciones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_transacciones_fecha'))
        batch_op.drop_index(batch_op.f('idx_transacciones_periodo'))

    op.drop_table('transacciones')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('email'))

    op.drop_table('usuarios')
    with op.batch_alter_table('presupuestos_familiares_anuales', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('familia_id'))

    op.drop_table('presupuestos_familiares_anuales')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('presupuestos_familiares_anuales',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('familia_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('año', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('estado', mysql.ENUM('activo', 'inactivo', 'eliminado'), server_default=sa.text("'activo'"), nullable=True),
    sa.Column('fecha_creacion', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('creador_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['creador_id'], ['usuarios.id'], name='presupuestos_familiares_anuales_ibfk_2', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['familia_id'], ['familias.id'], name='presupuestos_familiares_anuales_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('presupuestos_familiares_anuales', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('familia_id'), ['familia_id', 'nombre'], unique=True)

    op.create_table('usuarios',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('password_hash', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('avatar_url', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('fecha_creacion', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('email'), ['email'], unique=True)

    op.create_table('transacciones',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('periodo_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tipo', mysql.ENUM('ingreso', 'gasto', 'pago_deuda'), nullable=False),
    sa.Column('monto', mysql.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('fecha', sa.DATE(), nullable=False),
    sa.Column('descripcion', mysql.TEXT(), nullable=True),
    sa.Column('ingreso_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('gasto_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('deuda_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('creador_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.CheckConstraint('(`monto` > 0)', name='transacciones_chk_1'),
    sa.ForeignKeyConstraint(['creador_id'], ['usuarios.id'], name='transacciones_ibfk_5', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['deuda_id'], ['deudas.id'], name='transacciones_ibfk_4', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['gasto_id'], ['gastos.id'], name='transacciones_ibfk_3', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ingreso_id'], ['ingresos.id'], name='transacciones_ibfk_2', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['periodo_id'], ['periodos.id'], name='transacciones_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('transacciones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_transacciones_periodo'), ['periodo_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_transacciones_fecha'), ['fecha'], unique=False)

    op.create_table('periodos',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('presupuesto_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('fecha_inicio', sa.DATE(), nullable=False),
    sa.Column('fecha_fin', sa.DATE(), nullable=False),
    sa.Column('estado', mysql.ENUM('abierto', 'cerrado', 'planificado'), server_default=sa.text("'abierto'"), nullable=True),
    sa.ForeignKeyConstraint(['presupuesto_id'], ['presupuestos_familiares_anuales.id'], name='periodos_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('periodos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('presupuesto_id'), ['presupuesto_id', 'nombre'], unique=True)

    op.create_table('adjuntos',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('transaccion_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tipo', mysql.ENUM('imagen', 'pdf', 'otro'), nullable=False),
    sa.Column('url', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('nombre_archivo', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('fecha_subida', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['transaccion_id'], ['transacciones.id'], name=op.f('adjuntos_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('ingresos',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('presupuesto_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('categoria_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('nombre', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('monto', mysql.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('periodicidad', mysql.ENUM('mensual', 'anual', 'semestral', 'trimestral', 'único'), nullable=False),
    sa.Column('fecha_inicio', sa.DATE(), nullable=False),
    sa.Column('fecha_fin', sa.DATE(), nullable=True),
    sa.Column('descripcion', mysql.TEXT(), nullable=True),
    sa.Column('imagen_url', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('creador_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.CheckConstraint('(`monto` > 0)', name='ingresos_chk_1'),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias_ingresos.id'], name='ingresos_ibfk_2', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['creador_id'], ['usuarios.id'], name='ingresos_ibfk_3', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['presupuesto_id'], ['presupuestos_familiares_anuales.id'], name='ingresos_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('ingresos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_ingresos_presupuesto'), ['presupuesto_id'], unique=False)

    op.create_table('proyecciones',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('periodo_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ingreso_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('gasto_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('monto', mysql.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('tipo', mysql.ENUM('ingreso', 'gasto'), nullable=False),
    sa.Column('es_automatico', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=True),
    sa.Column('descripcion', mysql.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['gasto_id'], ['gastos.id'], name=op.f('proyecciones_ibfk_3'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ingreso_id'], ['ingresos.id'], name=op.f('proyecciones_ibfk_2'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['periodo_id'], ['periodos.id'], name=op.f('proyecciones_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('proyecciones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_proyecciones_periodo'), ['periodo_id'], unique=False)

    op.create_table('etiquetas',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('color', mysql.VARCHAR(length=7), server_default=sa.text("'#9b59b6'"), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name='etiquetas_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('etiquetas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('usuario_id'), ['usuario_id', 'nombre'], unique=True)

    op.create_table('usuarios_presupuestos',
    sa.Column('usuario_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('presupuesto_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('consultar', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=True),
    sa.Column('editar', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('eliminar_logico', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('eliminar_fisico', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('crear_entidades', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('es_owner', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['presupuesto_id'], ['presupuestos_familiares_anuales.id'], name=op.f('usuarios_presupuestos_ibfk_2'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('usuarios_presupuestos_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('usuario_id', 'presupuesto_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('categorias_ingresos',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('descripcion', mysql.TEXT(), nullable=True),
    sa.Column('icono_url', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('color', mysql.VARCHAR(length=7), server_default=sa.text("'#2ecc71'"), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name='categorias_ingresos_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('categorias_ingresos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('usuario_id'), ['usuario_id', 'nombre'], unique=True)

    op.create_table('usuarios_familias',
    sa.Column('usuario_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('familia_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rol', mysql.ENUM('admin', 'miembro', 'invitado'), nullable=False),
    sa.Column('fecha_union', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['familia_id'], ['familias.id'], name=op.f('usuarios_familias_ibfk_2'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('usuarios_familias_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('usuario_id', 'familia_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('planes_pago',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('deuda_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('monto', mysql.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('porcentaje', mysql.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('fecha_esperada', sa.DATE(), nullable=False),
    sa.Column('estado', mysql.ENUM('pendiente', 'pagado', 'atrasado'), server_default=sa.text("'pendiente'"), nullable=True),
    sa.Column('transaccion_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['deuda_id'], ['deudas.id'], name=op.f('planes_pago_ibfk_1'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transaccion_id'], ['transacciones.id'], name=op.f('planes_pago_ibfk_2'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('etiquetas_transacciones',
    sa.Column('transaccion_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('etiqueta_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['etiqueta_id'], ['etiquetas.id'], name=op.f('etiquetas_transacciones_ibfk_2'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transaccion_id'], ['transacciones.id'], name=op.f('etiquetas_transacciones_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('transaccion_id', 'etiqueta_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('familias',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('codigo_invitacion', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('moneda_principal', mysql.VARCHAR(length=3), server_default=sa.text("'COP'"), nullable=True),
    sa.Column('fecha_creacion', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('familias', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('codigo_invitacion'), ['codigo_invitacion'], unique=True)

    op.create_table('gastos',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('presupuesto_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('categoria_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('monto', mysql.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('periodicidad', mysql.ENUM('mensual', 'anual', 'semestral', 'trimestral', 'único'), nullable=False),
    sa.Column('fecha_inicio', sa.DATE(), nullable=False),
    sa.Column('fecha_fin', sa.DATE(), nullable=True),
    sa.Column('descripcion', mysql.TEXT(), nullable=True),
    sa.Column('imagen_url', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('creador_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.CheckConstraint('(`monto` > 0)', name=op.f('gastos_chk_1')),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias_gastos.id'], name=op.f('gastos_ibfk_2'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['creador_id'], ['usuarios.id'], name=op.f('gastos_ibfk_3'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['presupuesto_id'], ['presupuestos_familiares_anuales.id'], name=op.f('gastos_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('gastos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_gastos_presupuesto'), ['presupuesto_id'], unique=False)

    op.create_table('categorias_gastos',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('descripcion', mysql.TEXT(), nullable=True),
    sa.Column('icono_url', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('color', mysql.VARCHAR(length=7), server_default=sa.text("'#3498db'"), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('categorias_gastos_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('categorias_gastos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('usuario_id'), ['usuario_id', 'nombre'], unique=True)

    op.create_table('deudas',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('presupuesto_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('monto_total', mysql.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('monto_pendiente', mysql.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('tasa_interes', mysql.DECIMAL(precision=5, scale=2), server_default=sa.text("'0.00'"), nullable=True),
    sa.Column('fecha_inicio', sa.DATE(), nullable=False),
    sa.Column('fecha_fin', sa.DATE(), nullable=True),
    sa.Column('descripcion', mysql.TEXT(), nullable=True),
    sa.Column('creador_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.CheckConstraint('(`monto_pendiente` >= 0)', name=op.f('deudas_chk_2')),
    sa.CheckConstraint('(`monto_total` > 0)', name=op.f('deudas_chk_1')),
    sa.ForeignKeyConstraint(['creador_id'], ['usuarios.id'], name=op.f('deudas_ibfk_2'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['presupuesto_id'], ['presupuestos_familiares_anuales.id'], name=op.f('deudas_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
